# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Unique Identifier'),
        ),
    ]
