# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condiment',
            name='slug',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='slug',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='size',
            name='slug',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='slug',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Unique Identifier'),
        ),
        migrations.AlterUniqueTogether(
            name='sizeditemprice',
            unique_together=set([('item', 'size')]),
        ),
    ]
