# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180728_0744'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='condiment',
            unique_together=set([('title', 'group')]),
        ),
    ]
