# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('OUTFORDELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='ONGOING', max_length=20),
        ),
    ]
