# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180728_0757'),
        ('order', '0004_auto_20180806_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.Size'),
            preserve_default=False,
        ),
    ]
